version: "3.9"
services:
  kt-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kt
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
